# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Stat 133
tagline:          'UCB - Stat 133'
description:      'Concepts in Computing with Data'
url:              http://snowdj.github.io/stat133/
baseurl:          http://snowdj.github.io/stat133/

author:
  name:           'Gaston Sanchez'
  url:            http://snowdj.github.io/stat133

paginate:         5

# Custom vars
version:          Fall 2016

github:
  repo:           https://github.com/ucb-stat133/stat133-fall-2016
